version: '3.4'

services:
  # netty:
  #   image: netty
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - redis
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "redis"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}  # --notify-keyspace-events Ex
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

